insert into skill(name, link, proficiency, description) values ('Adobe Photoshop/Adobe Illustrator/Figma/Sketch', 'https://www.harinkim-design.com', '고급', '디지털 공간에서 사용자 경험을 최우선으로 고려하여 직관적이고 아름다운 웹 디자인을 구현하는 웹디자이너입니다.');
insert into skill(name, link, proficiency, description) values ('Java/Spring Framework/Docker/MySQL', 'https://www.github.com/daeunjeong520/', '고급', '자바와 서버 사이의 완벽한 조화를 이루며 안정적이고 확장 가능한 시스템을 구축하는 서버 개발자입니다.');
insert into skill(name, link, proficiency, description) values ('Adobe XD/Sketch/Figma', 'https://www.github.com/daeunjeong520/', '중급', '사용자 경험을 우선시하며 직관적이고 매력적인 인터페이스를 디자인하는 UX/UI 디자이너입니다.');
insert into skill(name, link, proficiency, description) values ('Android/Kotlin', 'https://www.github.com/daeunjeong520/', '고급', '안드로이드 플랫폼에서 혁신적이고 사용자 중심의 모바일 애플리케이션을 개발하는 전문가입니다.');
insert into skill(name, link, proficiency, description) values ('Adobe XD/Sketch/Figma', 'https://www.github.com/daeunjeong520/', '중급', '창의적인 디자인과 사용자 중심의 접근 방식으로 혁신적인 디지털 경험을 제공하는 전문가입니다.');
insert into skill(name, link, proficiency, description) values ('Android/Kotlin', 'https://www.github.com/daeunjeong520/', '중급', '최신 안드로이드 기술을 활용해 안정적이고 직관적인 앱을 설계하는 안드로이드 개발자입니다.');
insert into skill(name, link, proficiency, description) values ('HTML/CSS/JavaScript', 'https://www.github.com/daeunjeong520/', '초급', '정교한 HTML/CSS 코드와 세련된 디자인으로 웹 페이지의 시각적 완성도를 높이는 웹 퍼블리셔입니다.');
insert into skill(name, link, proficiency, description) values ('Adobe XD/Sketch/Figma', 'https://www.github.com/daeunjeong520/', '중급', '디자인과 기능의 완벽한 균형을 통해 사용자와의 소통을 최적화하는 UX/UI 디자이너입니다.');
insert into skill(name, link, proficiency, description) values ('Java/Spring Framework/PostgreSQL/AWS', 'https://www.github.com/daeunjeong520/', '고급', '효율적이고 유지보수가 용이한 서버 솔루션을 설계하는 자바 기반 서버 개발자입니다.');
insert into skill(name, link, proficiency, description) values ('HTML/CSS/JavaScript', 'https://www.github.com/daeunjeong520/', '초급', '웹 표준과 크로스 브라우저 호환성을 고려하여 매끄럽고 사용자 친화적인 웹 페이지를 구현하는 웹 퍼블리셔입니다.');

insert into freelancer(name, email, encrypted_pwd, phone_number, job_group, job, work_style, career_year, has_career, star_rating, profile_img, skill_id, fcm_token) values ('김하린', 'kimharin@gmail.com', 'password', '010-1234-5678', '디자인', '웹 디자이너', '원격/상주', 7, true, 4.9, 'usere', 1, 'dbLcWfDZSnWM0GDsLzRs7i:APA91bFZejBcsGzE0OKhojbQDBKYcjpYnrKqSrVWmG_3l3pRVvaZdHLxJEZjp6xMl1G9UHGZJKxdMWiA7hBMCddXKYeeNA35m04Uqxw_-rQGufj6ZDOVaqWlY3h6PsHT4zBYs-KdrOQ1');
insert into freelancer(name, email, encrypted_pwd, phone_number, job_group, job, work_style, career_year, has_career, star_rating, profile_img, skill_id, fcm_token) values ('이도현', 'dohyun@gmail', 'password', '010-0814-0814', '개발', '서버 개발자, 웹 개발자', '상주', 3, true, 4.5, 'userb', 2, 'dbLcWfDZSnWM0GDsLzRs7i:APA91bFZejBcsGzE0OKhojbQDBKYcjpYnrKqSrVWmG_3l3pRVvaZdHLxJEZjp6xMl1G9UHGZJKxdMWiA7hBMCddXKYeeNA35m04Uqxw_-rQGufj6ZDOVaqWlY3h6PsHT4zBYs-KdrOQ1');
insert into freelancer(name, email, encrypted_pwd, phone_number, job_group, job, work_style, career_year, has_career, star_rating, profile_img, skill_id, fcm_token) values ('박유진', 'parkyuin@gmail.com', 'password', '010-1234-5678', '디자인', 'UI/UX 디자이너', '원격/상주', 6, true, 4.9, 'userc', 3, 'dbLcWfDZSnWM0GDsLzRs7i:APA91bFZejBcsGzE0OKhojbQDBKYcjpYnrKqSrVWmG_3l3pRVvaZdHLxJEZjp6xMl1G9UHGZJKxdMWiA7hBMCddXKYeeNA35m04Uqxw_-rQGufj6ZDOVaqWlY3h6PsHT4zBYs-KdrOQ1');
insert into freelancer(name, email, encrypted_pwd, phone_number, job_group, job, work_style, career_year, has_career, star_rating, profile_img, skill_id, fcm_token) values ('정수호', 'jeongsuho@gmail.com', 'password', '010-0814-0814', '개발', '안드로이드 개발자', '상주', 2, true, 4.2, 'userd', 4, 'dbLcWfDZSnWM0GDsLzRs7i:APA91bFZejBcsGzE0OKhojbQDBKYcjpYnrKqSrVWmG_3l3pRVvaZdHLxJEZjp6xMl1G9UHGZJKxdMWiA7hBMCddXKYeeNA35m04Uqxw_-rQGufj6ZDOVaqWlY3h6PsHT4zBYs-KdrOQ1');
insert into freelancer(name, email, encrypted_pwd, phone_number, job_group, job, work_style, career_year, has_career, star_rating, profile_img, skill_id, fcm_token) values ('최아름', 'areum@gmail.com', 'password', '010-1234-5678', '디자인', 'UI/UX 디자이너', '원격/상주', 7, true, 4.8, 'usera', 5, 'dbLcWfDZSnWM0GDsLzRs7i:APA91bFZejBcsGzE0OKhojbQDBKYcjpYnrKqSrVWmG_3l3pRVvaZdHLxJEZjp6xMl1G9UHGZJKxdMWiA7hBMCddXKYeeNA35m04Uqxw_-rQGufj6ZDOVaqWlY3h6PsHT4zBYs-KdrOQ1');
insert into freelancer(name, email, encrypted_pwd, phone_number, job_group, job, work_style, career_year, has_career, star_rating, profile_img, skill_id, fcm_token) values ('강민호', 'kangminho@gmail.com', 'password', '010-0814-0814', '개발', '안드로이드 개발자', '상주', 5, true, 4.5, 'userf', 6, 'dbLcWfDZSnWM0GDsLzRs7i:APA91bFZejBcsGzE0OKhojbQDBKYcjpYnrKqSrVWmG_3l3pRVvaZdHLxJEZjp6xMl1G9UHGZJKxdMWiA7hBMCddXKYeeNA35m04Uqxw_-rQGufj6ZDOVaqWlY3h6PsHT4zBYs-KdrOQ1');
insert into freelancer(name, email, encrypted_pwd, phone_number, job_group, job, work_style, career_year, has_career, star_rating, profile_img, skill_id, fcm_token) values ('조은비', 'choeunbi@gmail.com', 'password', '010-1234-5678', '디자인', '웹 디자이너', '원격/상주', 6, true, 4.9, 'userg', 7, 'dbLcWfDZSnWM0GDsLzRs7i:APA91bFZejBcsGzE0OKhojbQDBKYcjpYnrKqSrVWmG_3l3pRVvaZdHLxJEZjp6xMl1G9UHGZJKxdMWiA7hBMCddXKYeeNA35m04Uqxw_-rQGufj6ZDOVaqWlY3h6PsHT4zBYs-KdrOQ1');
insert into freelancer(name, email, encrypted_pwd, phone_number, job_group, job, work_style, career_year, has_career, star_rating, profile_img, skill_id, fcm_token) values ('윤재원', 'yoonjeawon@gmail.com', 'password', '010-0814-0814', '디자인', 'UI/UX 디자이너', '상주', 2, true, 4.2, 'userh', 8, 'dbLcWfDZSnWM0GDsLzRs7i:APA91bFZejBcsGzE0OKhojbQDBKYcjpYnrKqSrVWmG_3l3pRVvaZdHLxJEZjp6xMl1G9UHGZJKxdMWiA7hBMCddXKYeeNA35m04Uqxw_-rQGufj6ZDOVaqWlY3h6PsHT4zBYs-KdrOQ1');
insert into freelancer(name, email, encrypted_pwd, phone_number, job_group, job, work_style, career_year, has_career, star_rating, profile_img, skill_id, fcm_token) values ('임서준', 'iimseojun@gmail.com', 'password', '010-1234-5678', '개발', '서버 개발자', '원격/상주', 10, true, 4.8, 'useri', 9, 'dbLcWfDZSnWM0GDsLzRs7i:APA91bFZejBcsGzE0OKhojbQDBKYcjpYnrKqSrVWmG_3l3pRVvaZdHLxJEZjp6xMl1G9UHGZJKxdMWiA7hBMCddXKYeeNA35m04Uqxw_-rQGufj6ZDOVaqWlY3h6PsHT4zBYs-KdrOQ1');
insert into freelancer(name, email, encrypted_pwd, phone_number, job_group, job, work_style, career_year, has_career, star_rating, profile_img, skill_id, fcm_token) values ('오하연', 'ohayeon@gmail.com', 'password', '010-0814-0814', '디자인', '웹 디자이너', '상주', 4, true, 4.5, 'userj', 10, 'dbLcWfDZSnWM0GDsLzRs7i:APA91bFZejBcsGzE0OKhojbQDBKYcjpYnrKqSrVWmG_3l3pRVvaZdHLxJEZjp6xMl1G9UHGZJKxdMWiA7hBMCddXKYeeNA35m04Uqxw_-rQGufj6ZDOVaqWlY3h6PsHT4zBYs-KdrOQ1');

insert into client(email, encrypted_pwd, company_name, manager_name, manager_phone, manager_email, star_rating) values ('jungde1345@naver.com', 'password', '미래탐구', '김지훈', '010-1234-5678', 'jungde1345@naver.com', 4.5);
insert into client(email, encrypted_pwd, company_name, manager_name, manager_phone, manager_email, star_rating) values ('jungde1345@naver.com', 'password', '디지털별빛', '최민하', '010-1234-5678', 'jungde1345@gmail.com', 5.0);
insert into client(email, encrypted_pwd, company_name, manager_name, manager_phone, manager_email, star_rating) values ('jungde1345@naver.com', 'password', '넥스트이노베이션', '이수민', '010-1234-5678', 'jungde1345@gmail.com', 4.8);

insert into project(client_id, title, description, start_date, end_date, period, job_group, job, skill, pay, want_career_year, progress, work_style, client_status) values (1, '북스토어 상세페이지 수정 및 퍼블리싱 - CSS, HTML', '상품의 상세 페이지를 새로운 스토어의 레이아웃에 맞게 이미지와 CSS 등의 디자인 수정 - 기존 정보를 편집하여 구성하고, 모바일에 최적화한 퍼블리싱 작업을 진행\n(분량이 많고 빠르게 진행되어야 해서 리소스 확보를 위해 프로젝트 의뢰) \n 최소 20종의 상품에 대한 상세페이지 작업 필요 \n 매 상세 페이지마다 새로운 디자인이 필요한 상황이 아니고,공통 적용하는 레이아웃과 템플릿을 드리면, 이를 기준으로 기존 정보를 재구성하고 디자인을 완성하고쇼피파이에서 퍼블리싱 작업을 진행하는 업무 \n단, 매 상세 페이지마다 새로운 디자인이 필요한 상황이 아니고, 공통 적용하는 레이아웃과 템플릿을 드리면, 이를 기준으로 기존 정보를 재구성하고 디자인을 완성하고쇼피파이에서 퍼블리싱 작업을 진행하는 업무', '2024-09-30', '2024-10-30', 1, '디자인', '웹 디자이너', 'HTML/CSS/Figma', 300, 2 ,0.0, '원격', 'CREATE');
insert into project(client_id, title, description, start_date, end_date, period, job_group, job, skill, pay, want_career_year, progress, work_style, client_status) values(2,'한국은행 CBDC 활용성 테스트 시스템 구축 - Java', '한국은행 CBDC 활용성 테스트 시스템 구축. 10월 프로젝트 시작 \n중급개발자(2명) - 참여기관 디지털 통화 관리시스템 업무 개발\n한국은행, 참여은행간 디지털 접속 관리업무(로그인, 고객관리, 관리자계정관리, 이력관리등)', '2024-10-02', '2025-02-10', 5, '개발', '서버개발/자바개발', 'Java/Spring/MySQL', 525, 5, 0.0, '상주', 'CREATE');
insert into project(client_id, title, description, start_date, end_date, period, job_group, job, skill, pay, want_career_year, progress, work_style, client_status) values(3, '레쿠에 쇼핑몰 런칭 준비 (상세페이지 디자인) - HTML, After Effect', '- 상세페이지 디자인 : 현재 브라반티아 공홈에 런칭한 상품 참고\n- 카페24 홈페이지 스킨 구매 후 커스터마이징\n- 상품 등록\n12개 상품군 상품페이지 디자인(전체 50~60개 상품 페이지 작업), 썸네일 제작: 상페 기본 템플릿 있고, 현재 4개 제품 상페 있어서 베리에이션 가능\n1개 상품군에 사이즈, 색상, 종류별 2~10개 상품이 있음(주요디자인은 동일하고, 상품군 별 내용 디자인 필요하고 나머지는 이미지와 카피 등 단순 수정 가능)','2024-09-23', '2024-12-31', 3, '디자인', '웹디자이너', 'HTML/After Effect/Adobe Photoshop', 250, 3, 0.0, '원격', 'CREATE');
insert into project(client_id, title, description, start_date, end_date, period, job_group, job, skill, pay, want_career_year, progress, work_style, client_status) values(3, '배송대행지 웹서비스 클라이언트 개발 - AWS, React.js', '- Kfriday 역직구 배송대행지 웹서비스 UI 개선 및 고도화\n- 배대지, 다해줌 등의 서비스를 제공하는 ‘몰테일’과 유사한 서비스입니다.\n세부 업무 범위\n- 사용자 로그인/회원가입\n- 배송대행지 관련 기능 전반: 구매/보관/배송/검수/재포장 조회/검색/요청/수정 등', '2024-09-23', '2024-12-30', 3, '개발', '프론트앤드개발', 'AWS/React.js/Next.js', 800, 4, 0.0, '원격/상주', 'CREATE');